/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_values_Creator */

#ifndef _Included_at_renehollander_duktape_values_Creator
#define _Included_at_renehollander_duktape_values_Creator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_renehollander_duktape_values_Creator
 * Method:    createEmptyObject
 * Signature: (Lat/renehollander/duktape/Duktape;)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_values_Creator_createEmptyObject
  (JNIEnv *, jclass, jobject);

/*
 * Class:     at_renehollander_duktape_values_Creator
 * Method:    createEmptyArray
 * Signature: (Lat/renehollander/duktape/Duktape;)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_values_Creator_createEmptyArray
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
