/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_values_DukJavaFunction */

#ifndef _Included_at_renehollander_duktape_values_DukJavaFunction
#define _Included_at_renehollander_duktape_values_DukJavaFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_renehollander_duktape_values_DukJavaFunction
 * Method:    _createAndReference
 * Signature: (JLjava/lang/reflect/Method;ILjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_values_DukJavaFunction__1createAndReference
        (JNIEnv *, jclass, jlong, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
