/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_values_DukFunction */

#ifndef _Included_at_renehollander_duktape_values_DukFunction
#define _Included_at_renehollander_duktape_values_DukFunction
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
