/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_values_DukReferencedValue */

#ifndef _Included_at_renehollander_duktape_values_DukReferencedValue
#define _Included_at_renehollander_duktape_values_DukReferencedValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_renehollander_duktape_values_DukReferencedValue
 * Method:    unref
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukReferencedValue_unref
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
