/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_values_DukArray */

#ifndef _Included_at_renehollander_duktape_values_DukArray
#define _Included_at_renehollander_duktape_values_DukArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    createEmptyArray
 * Signature: (Lat/renehollander/duktape/Duktape;)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_values_DukArray_createEmptyArray
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
