/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_values_DukArray */

#ifndef _Included_at_renehollander_duktape_values_DukArray
#define _Included_at_renehollander_duktape_values_DukArray
#ifdef __cplusplus
extern "C" {
#endif
#undef at_renehollander_duktape_values_DukArray_MAX_ARRAY_SIZE
#define at_renehollander_duktape_values_DukArray_MAX_ARRAY_SIZE 2147483639L
/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _createArray
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_values_DukArray__1createArray
  (JNIEnv *, jclass, jlong);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _size
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_values_DukArray__1size
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _toJSON
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_renehollander_duktape_values_DukArray__1toJSON
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _get
 * Signature: (JILat/renehollander/duktape/Duktape;I)Lat/renehollander/duktape/values/DukValue;
 */
JNIEXPORT jobject JNICALL Java_at_renehollander_duktape_values_DukArray__1get
  (JNIEnv *, jclass, jlong, jint, jobject, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addDouble
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addDouble
  (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addBoolean
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addBoolean
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addString
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addString
  (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addUndefined
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addUndefined
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addNull
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addNull
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addReference
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addReference
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
