/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_values_DukError */

#ifndef _Included_at_renehollander_duktape_values_DukError
#define _Included_at_renehollander_duktape_values_DukError
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_renehollander_duktape_values_DukError
 * Method:    _createDukError
 * Signature: (JILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_values_DukError__1createDukError
        (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     at_renehollander_duktape_values_DukError
 * Method:    _getErrorCode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_values_DukError__1getErrorCode
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     at_renehollander_duktape_values_DukError
 * Method:    _getErrorMessage
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_renehollander_duktape_values_DukError__1getErrorMessage
        (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class at_renehollander_duktape_values_DukError_ErrorType */

#ifndef _Included_at_renehollander_duktape_values_DukError_ErrorType
#define _Included_at_renehollander_duktape_values_DukError_ErrorType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
