/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_values_DukArray */

#ifndef _Included_at_renehollander_duktape_values_DukArray
#define _Included_at_renehollander_duktape_values_DukArray
#ifdef __cplusplus
extern "C" {
#endif
#undef at_renehollander_duktape_values_DukArray_MAX_ARRAY_SIZE
#define at_renehollander_duktape_values_DukArray_MAX_ARRAY_SIZE 2147483639L
/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _createArray
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_values_DukArray__1createArray
        (JNIEnv *, jclass, jlong);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _size
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_values_DukArray__1size
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _toJSON
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_renehollander_duktape_values_DukArray__1toJSON
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _get
 * Signature: (JII)Lat/renehollander/duktape/values/DukValue;
 */
JNIEXPORT jobject JNICALL Java_at_renehollander_duktape_values_DukArray__1get
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _remove
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1remove
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addDouble
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addDouble__JID
        (JNIEnv *, jclass, jlong, jint, jdouble);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addBoolean
 * Signature: (JIZ)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addBoolean__JIZ
        (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addString
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addString__JILjava_lang_String_2
        (JNIEnv *, jclass, jlong, jint, jstring);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addUndefined
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addUndefined__JI
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addNull
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addNull__JI
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addReference
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addReference__JII
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addDouble
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addDouble__JIID
        (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addBoolean
 * Signature: (JIIZ)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addBoolean__JIIZ
        (JNIEnv *, jclass, jlong, jint, jint, jboolean);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addString
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addString__JIILjava_lang_String_2
        (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addUndefined
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addUndefined__JII
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addNull
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addNull__JII
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _addReference
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1addReference__JIII
        (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _setDouble
 * Signature: (JIID)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1setDouble
        (JNIEnv *, jclass, jlong, jint, jint, jdouble);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _setBoolean
 * Signature: (JIIZ)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1setBoolean
        (JNIEnv *, jclass, jlong, jint, jint, jboolean);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _setString
 * Signature: (JIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1setString
        (JNIEnv *, jclass, jlong, jint, jint, jstring);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _setUndefined
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1setUndefined
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _setNull
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1setNull
        (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     at_renehollander_duktape_values_DukArray
 * Method:    _setReference
 * Signature: (JIII)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_values_DukArray__1setReference
        (JNIEnv *, jclass, jlong, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
