/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_NativeHelper */

#ifndef _Included_at_renehollander_duktape_NativeHelper
#define _Included_at_renehollander_duktape_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_renehollander_duktape_NativeHelper
 * Method:    _unref
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_NativeHelper__1unref
        (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     at_renehollander_duktape_NativeHelper
 * Method:    _mark_for_unref
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_NativeHelper__1mark_1for_1unref
        (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
