/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_NativeHelper */

#ifndef _Included_at_renehollander_duktape_NativeHelper
#define _Included_at_renehollander_duktape_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_renehollander_duktape_NativeHelper
 * Method:    unref
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_NativeHelper_unref
        (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
