/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_value_object_DukBuffer */

#ifndef _Included_at_renehollander_duktape_value_object_DukBuffer
#define _Included_at_renehollander_duktape_value_object_DukBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_renehollander_duktape_value_object_DukBuffer
 * Method:    _createDukBuffer
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_value_object_DukBuffer__1createDukBuffer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     at_renehollander_duktape_value_object_DukBuffer
 * Method:    _getByteBuffer
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_at_renehollander_duktape_value_object_DukBuffer__1getByteBuffer
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
