/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_value_object_DukFunction */

#ifndef _Included_at_renehollander_duktape_value_object_DukFunction
#define _Included_at_renehollander_duktape_value_object_DukFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_renehollander_duktape_value_object_DukFunction
 * Method:    _invoke
 * Signature: (JI[Lat/renehollander/duktape/value/DukValue;)Lat/renehollander/duktape/value/DukValue;
 */
JNIEXPORT jobject JNICALL Java_at_renehollander_duktape_value_object_DukFunction__1invoke
  (JNIEnv *, jclass, jlong, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
