/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_Duktape */

#ifndef _Included_at_renehollander_duktape_Duktape
#define _Included_at_renehollander_duktape_Duktape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_renehollander_duktape_Duktape
 * Method:    _getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_at_renehollander_duktape_Duktape__1getVersion
  (JNIEnv *, jclass);

/*
 * Class:     at_renehollander_duktape_Duktape
 * Method:    _createContext
 * Signature: (Lat/renehollander/duktape/Duktape;)J
 */
JNIEXPORT jlong JNICALL Java_at_renehollander_duktape_Duktape__1createContext
  (JNIEnv *, jclass, jobject);

/*
 * Class:     at_renehollander_duktape_Duktape
 * Method:    _destroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_Duktape__1destroyContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     at_renehollander_duktape_Duktape
 * Method:    _getRefCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_at_renehollander_duktape_Duktape__1getRefCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     at_renehollander_duktape_Duktape
 * Method:    _gc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_Duktape__1gc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     at_renehollander_duktape_Duktape
 * Method:    _getHeapUsage
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_at_renehollander_duktape_Duktape__1getHeapUsage
  (JNIEnv *, jclass, jlong);

/*
 * Class:     at_renehollander_duktape_Duktape
 * Method:    _execute
 * Signature: (JLjava/lang/String;)Lat/renehollander/duktape/value/DukValue;
 */
JNIEXPORT jobject JNICALL Java_at_renehollander_duktape_Duktape__1execute
  (JNIEnv *, jclass, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
