/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_renehollander_duktape_Duktape */

#ifndef _Included_at_renehollander_duktape_Duktape
#define _Included_at_renehollander_duktape_Duktape
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_renehollander_duktape_Duktape
 * Method:    execute
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_at_renehollander_duktape_Duktape_execute
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
